<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Salary Slip {{ $salary->reference }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .action-buttons { max-width: 700px; margin: 0 auto 20px; display: flex; gap: 10px; justify-content: center; }
        .btn { padding: 12px 24px; border: none; border-radius: 5px; cursor: pointer; font-size: 16px; text-decoration: none; display: inline-block; text-align: center; }
        .btn-back { background: #6c757d; color: white; }
        .btn-print { background: #007bff; color: white; }
        .slip-container { max-width: 700px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        .slip-header { text-align: center; border-bottom: 3px solid #333; padding-bottom: 15px; margin-bottom: 25px; }
        .slip-header h1 { font-size: 28px; letter-spacing: 2px; }
        .slip-header .academy { font-size: 14px; color: #555; margin-top: 4px; }
        .slip-header .ref { font-size: 13px; color: #888; margin-top: 4px; }
        .section-title { font-size: 14px; font-weight: bold; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin: 22px 0 12px; }
        table.details { width: 100%; border-collapse: collapse; }
        table.details td { padding: 8px 4px; font-size: 14px; }
        table.details td:first-child { color: #555; width: 45%; }
        table.details td:last-child { font-weight: bold; text-align: right; }
        .gross-row { background: #f0f4ff; border-top: 2px solid #333; }
        .gross-row td { font-size: 18px !important; padding: 12px 6px !important; }
        .notes { margin-top: 20px; font-size: 13px; color: #666; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #999; }
        @media print {
            body { background: white; padding: 0; }
            .action-buttons { display: none; }
            .slip-container { box-shadow: none; padding: 10px; }
        }
        @page { size: A4; margin: 15mm; }
    </style>
</head>
<body>
    <div class="action-buttons">
        <a href="{{ route('salaries.index') }}" class="btn btn-back">← Back to Teacher Salaries</a>
        <button onclick="window.print()" class="btn btn-print">🖨️ Print Salary Slip</button>
    </div>

    <div class="slip-container">
        <div class="slip-header">
            <h1>SALARY SLIP</h1>
            <div class="academy">{{ config('app.name') }}</div>
            <div class="ref">{{ $salary->reference }}</div>
        </div>

        <div class="section-title">Teacher</div>
        <table class="details">
            <tr><td>Teacher Name</td><td>{{ $salary->teacher_name }}</td></tr>
            <tr><td>Pay Period</td><td>{{ $salary->date_from->format('d M Y') }} — {{ $salary->date_to->format('d M Y') }}</td></tr>
        </table>

        <div class="section-title">Earnings</div>
        <table class="details">
            <tr><td>Hourly Rate</td><td>£{{ number_format($salary->hourly_rate, 2) }}</td></tr>
            <tr><td>Attendance Sessions</td><td>{{ $salary->sessions }}</td></tr>
            <tr><td>Hours Worked</td><td>{{ $salary->hours }} hours</td></tr>
            <tr class="gross-row"><td>Gross Salary</td><td>£{{ number_format($salary->gross, 2) }}</td></tr>
        </table>

        <div class="section-title">Payment</div>
        <table class="details">
            <tr><td>Payment Date</td><td>{{ $salary->payment_date->format('d M Y') }}</td></tr>
            <tr><td>Payment Method</td><td>{{ $salary->payment_method === 'Bank' ? 'Bank Transfer' : $salary->payment_method }}</td></tr>
            <tr><td>Status</td><td>{{ strtoupper($salary->status) }}</td></tr>
        </table>

        @if($salary->notes)
        <div class="notes"><strong>Notes:</strong> {{ $salary->notes }}</div>
        @endif

        <div class="footer">Generated by {{ config('app.name') }} — {{ $salary->reference }}</div>
    </div>
</body>
</html>
